site_name: Neographviz docs
site_url: https://icfly2.github.io/neographviz/
nav:
    - Home: index.md
    - Viz: viz.md
    - About: about.md

theme:
  name: "readthedocs"

plugins:
- search
- mkdocstrings